development:
  adapter:  mysql2
  database: rampup_development
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter:  mysql2
  database: rampup_test
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
