User.find_or_create_by_username('admin', :password => 'password', :role => 'admin')
User.find_or_create_by_username('superadmin', :password => 'password', :role => 'superadmin')
User.find_or_create_by_username('employee', :password => 'password', :role => 'employee')

india = Country.find_or_create_by_name(:name=>'India')
usa = Country.find_or_create_by_name(:name=>'USA')
uk = Country.find_or_create_by_name(:name=>'UK')
nepal = Country.find_or_create_by_name(:name=>'Nepal')
australia = Country.find_or_create_by_name(:name=>'Australia')
brazil = Country.find_or_create_by_name(:name=>'Brazil')
netherlands = Country.find_or_create_by_name(:name=>'Netherlands')
costa_rica = Country.find_or_create_by_name(:name=>'Costa Rica')
china = Country.find_or_create_by_name(:name=>'China')
canada = Country.find_or_create_by_name(:name=>'Canada')
germany = Country.find_or_create_by_name(:name=>'Germany')
sweden = Country.find_or_create_by_name(:name=>'Sweden')
us = Country.find_or_create_by_name(:name=>'US')

Location.find_or_create_by_id(1, :name => 'Chennai',:countries_id => india.id)
Location.find_or_create_by_id(2, :name => 'Bangalore', :countries_id => india.id)
Location.find_or_create_by_id(3, :name =>'Pune', :countries_id => india.id)
Location.find_or_create_by_id(4, :name =>'Bangalore 1', :countries_id => india.id)
Location.find_or_create_by_id(5, :name =>'Bangalore 2', :countries_id => india.id)
Location.find_or_create_by_id(6, :name =>'Calgary', :countries_id => canada.id)
Location.find_or_create_by_id(7, :name =>'Delhi-Gurgoan', :countries_id => india.id)
Location.find_or_create_by_id(8, :name =>'Sydney', :countries_id => australia.id)
Location.find_or_create_by_id(9, :name =>'London', :countries_id => uk.id)
Location.find_or_create_by_id(10, :name =>'Chicago', :countries_id => us.id)
Location.find_or_create_by_id(11, :name =>'Delhi/Gurgoan', :countries_id => india.id)
Location.find_or_create_by_id(12, :name =>'Brisbane', :countries_id => australia.id)
Location.find_or_create_by_id(13, :name =>'Melbourne', :countries_id => australia.id)
Location.find_or_create_by_id(14, :name =>'San Francisco', :countries_id => us.id)
Location.find_or_create_by_id(15, :name =>'New York', :countries_id => us.id)
Location.find_or_create_by_id(16, :name =>'Gurgaon', :countries_id => india.id)
Location.find_or_create_by_id(17, :name =>'Porto Alegre', :countries_id => brazil.id)
Location.find_or_create_by_id(18, :name =>'Atlanta', :countries_id => us.id)
Location.find_or_create_by_id(19, :name =>'Beijing', :countries_id => china.id)
Location.find_or_create_by_id(20, :name =>'Delhi', :countries_id => india.id)
Location.find_or_create_by_id(21, :name =>'Hamburg', :countries_id => germany.id)
Location.find_or_create_by_id(22, :name =>'Manchester', :countries_id => uk.id)
Location.find_or_create_by_id(23, :name =>'Nashville', :countries_id => us.id)
Location.find_or_create_by_id(24, :name =>'NY-NJ Home Offices', :countries_id => us.id)
Location.find_or_create_by_id(25, :name =>'Ohio', :countries_id => us.id)
Location.find_or_create_by_id(26, :name =>'Perth', :countries_id => australia.id)
Location.find_or_create_by_id(27, :name =>'Stockholm', :countries_id => sweden.id)
Location.find_or_create_by_id(28, :name =>'Sunnyvale', :countries_id => us.id)
Location.find_or_create_by_id(29, :name =>'Toronto', :countries_id => canada.id)
Location.find_or_create_by_id(30, :name =>'US Corp', :countries_id => us.id)
Location.find_or_create_by_id(31, :name =>'X\'ian', :countries_id => china.id)

College.find_or_create_by_name(:name=>'IIT-Kanpur')
College.find_or_create_by_name(:name=>'IIT-Kharagpur')
College.find_or_create_by_name(:name=>'IIT-Bombay')
College.find_or_create_by_name(:name=>'IIT-Delhi')
College.find_or_create_by_name(:name=>'IIT-Roorkee')
College.find_or_create_by_name(:name=>'IIT-Guwahati')
College.find_or_create_by_name(:name=>'NIT-Allahabad')
College.find_or_create_by_name(:name=>'NIT-Surathkal')
College.find_or_create_by_name(:name=>'NIT-Calicut')

Branch.find_or_create_by_name(:name=>'industrial and mgmnt eng')
Branch.find_or_create_by_name(:name=>'mechanical eng')
Branch.find_or_create_by_name(:name=>'electronics and comm eng')
Branch.find_or_create_by_name(:name=>'computer science eng')
Branch.find_or_create_by_name(:name=>'information technology eng')
Branch.find_or_create_by_name(:name=>'electrical eng')
Branch.find_or_create_by_name(:name=>'computer application')

Degree.find_or_create_by_name(:name=>'BCom', :category=>'Bachelors-Arts/Sci/Comm')
Degree.find_or_create_by_name(:name=>'BCS', :category=>'Bachelors-Arts/Sci/Comm')
Degree.find_or_create_by_name(:name=>'BIT', :category=>'Bachelors-Engg')
Degree.find_or_create_by_name(:name=>'BE', :category=>'Bachelors-Engg')
Degree.find_or_create_by_name(:name=>'BCA', :category=>'Bachelors-Engg')
Degree.find_or_create_by_name(:name=>'BTech', :category=>'Bachelors-Engg')
Degree.find_or_create_by_name(:name=>'BBA', :category=>'Bachelors-Mgmt')
Degree.find_or_create_by_name(:name=>'BBM', :category=>'Bachelors-Mgmt')
Degree.find_or_create_by_name(:name=>'MCA', :category=>'Masters-Engg')
Degree.find_or_create_by_name(:name=>'MBA', :category=>'Masters-Mgmt')

Technology.find_or_create_by_name(:name=>'Java')
Technology.find_or_create_by_name(:name=>'C')
Technology.find_or_create_by_name(:name=>'C++')
Technology.find_or_create_by_name(:name=>'RoR')
Technology.find_or_create_by_name(:name=>'Python')

Relation.find_or_create_by_name(:name=>'Father')
Relation.find_or_create_by_name(:name=>'Mother')
Relation.find_or_create_by_name(:name=>'Son')
Relation.find_or_create_by_name(:name=>'Daughter')
Relation.find_or_create_by_name(:name=>'Spouse')

Title.find_or_create_by_name(:name=> 'Developer')
Title.find_or_create_by_name(:name=> 'Account Manager')
Title.find_or_create_by_name(:name=> 'Administration Specialist')
Title.find_or_create_by_name(:name=> 'Graduate')
Title.find_or_create_by_name(:name=> 'Infrastructure Specialist')

VisaCategory.find_or_create_by_name(:name=>'US H1B')
VisaCategory.find_or_create_by_name(:name=>'US B1')
VisaCategory.find_or_create_by_name(:name=>'US L1A')
VisaCategory.find_or_create_by_name(:name=>'US L1B')
VisaCategory.find_or_create_by_name(:name=>'UK - Work Permit')
VisaCategory.find_or_create_by_name(:name=>'UK Business')
VisaCategory.find_or_create_by_name(:name=>'Schengen')
VisaCategory.find_or_create_by_name(:name=>'Australian - Business')
VisaCategory.find_or_create_by_name(:name=>'Australian - Work Permit')

State.find_or_create_by_name(:name=>'Karnataka')
State.find_or_create_by_name(:name=>'Uttar Pradesh')
State.find_or_create_by_name(:name=>'Haryana')
State.find_or_create_by_name(:name=>'Maharashtra')
State.find_or_create_by_name(:name=>'Delhi')
State.find_or_create_by_name(:name=>'Karnataka')

TemplateGenerator.find_or_create_by_name('Confidentiality Agreement - Deepa', :file_name => 'Confidentiality Agreement - Deepa.htm', :document_type => 1, :selected => 0, :created_at => '2009-09-08 17:50:48', :updated_at => '2009-10-05 21:23:41')
TemplateGenerator.find_or_create_by_name('Confidentiality Agreement - Sitaraman', :file_name => 'Confidentiality Agreement - Sitaraman.htm', :document_type => 1, :selected => 0, :created_at => '2009-09-08 17:51:08', :updated_at => '2009-09-22 13:23:38')
TemplateGenerator.find_or_create_by_name('Page 1 - Employee Data Sheet', :file_name =>'Page 1 - Employee Data Sheet.htm', :document_type => 1, :selected => 1, :created_at => '2009-09-08 17:51:27', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Page 5 - Life Insurance - Enrollment', :file_name =>'Page 5 - Life Insurance - Enrollment.htm', :document_type => 1, :selected => 1, :created_at => '2009-09-08 17:52:47', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Page 6 - Gratuity Nomination', :file_name =>'Page 6 - Gratuity Nomination.htm', :document_type => 1, :selected => 1, :created_at =>'2009-09-08 17:53:08', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Page 7 - Cellular Phone Waiver', :file_name =>'Page 7 - Cellular Phone Waiver.htm', :document_type => 1, :selected => 1, :created_at => '2009-09-08 17:53:27', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Page 8 - Vacation pay before it is earned-India', :file_name =>'Page 8 - Vacation pay before it is earned-India.htm', :document_type => 1, :selected => 1, :created_at => '2009-09-08 17:53:45', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Page 9 - Waiver of Negligence & Release', :file_name => 'Page 9 - Waiver of Negligence & Release.htm', :document_type => 1, :selected => 1, :created_at => '2009-09-08 17:54:05', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Page 10 & 11 - PF Nominataion and Declaration', :file_name =>'Page 10 & 11 - PF Nominataion and Declaration.htm', :document_type => 1, :selected => 1, :created_at => '2009-09-08 17:54:22', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Page 12 - Sexual Harassment Policy', :file_name => 'Page 12 - Sexual Harassment Policy.htm', :document_type => 1, :selected => 1, :created_at => '2009-09-08 17:54:38', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Address Proof', :file_name =>'Address Proof.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:55:04', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Bank Account Letter', :file_name => 'Bank Account Letter.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:55:23', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('China Biz Visa', :file_name => 'China Biz Visa.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:55:35', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Forex Purchase - Centurion Bank', :file_name =>'Forex Purchase - Centurion Bank.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:55:50', :updated_at =>'2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Forex Purchase - VKC', :file_name => 'Forex Purchase - VKC.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:56:13', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Forex Purchase - Weizmann', :file_name =>'Forex Purchase - Weizmann.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:56:29', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('H1B Cover Letter', :file_name => 'H1B Cover Letter.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:56:43', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Laptop Letter', :file_name =>'Laptop Letter.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:57:06', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('Oz Biz Visa', :file_name =>'Oz Biz Visa.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:57:20', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('UK Biz Visa', :file_name =>'UK Biz Visa.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:57:34', :updated_at => '2009-09-08 17:58:23')
TemplateGenerator.find_or_create_by_name('UK Work Permit', :file_name =>'UK Work Permit.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:57:49', :updated_at => '2009-09-08 19:33:27')
TemplateGenerator.find_or_create_by_name('US Biz Visa', :file_name =>'US Biz Visa.htm', :document_type => 0, :selected => 1, :created_at => '2009-09-08 17:58:02', :updated_at => '2009-09-08 19:33:27')
TemplateGenerator.find_or_create_by_name('Patricia Carlin', :file_name =>'CONFIDENTIALITY AGREEMENT - Patricia Carlin.htm', :document_type => 1, :selected => 0, :created_at => '2009-10-27 19:13:23', :updated_at => '2010-08-11 11:09:22')
TemplateGenerator.find_or_create_by_name('Leave Auth Letter', :file_name =>'LeaveAuthorization.htm', :document_type => 0, :selected => 1, :created_at => '2009-11-03 18:31:26', :updated_at => '2009-11-03 18:31:45')
TemplateGenerator.find_or_create_by_name('Page 2 & 3 - Dependent Undertaking', :file_name => 'Page 2 & 3 - Dependent Undertaking.htm', :document_type => 1, :selected => 1, :created_at => '2009-11-18 12:45:47', :updated_at => '2009-11-18 12:46:28')
TemplateGenerator.find_or_create_by_name('Confidentiality Agreement Anand Iyengar ', :file_name => 'CONFIDENTIALITY AGREEMENT - Anand Iyengar.htm', :document_type => 1, :selected => 1, :created_at => '2010-08-11 11:14:35', :updated_at => '2010-08-11 11:15:41')
TemplateGenerator.find_or_create_by_name('Page 4 - Medical Insurance - Enrollment', :file_name =>'Page 4 - Medical Insurance - Enrollment.htm', :document_type => 1, :selected => 1, :created_at => '2010-12-23 13:48:40', :updated_at =>'2010-12-27 13:09:56')

  
education_group = ChecklistGroup.find_or_create_by_description('Education Qualification Certificates', :order=>2)
visa_group = ChecklistGroup.find_or_create_by_description('Visa', :order=>3)
group1 = ChecklistGroup.find_or_create_by_description('Photographs', :order=>1)
tax_group = ChecklistGroup.find_or_create_by_description('Tax', :order=>4)
dependent_group = ChecklistGroup.find_or_create_by_description('Dependents Information', :order=>5)

NewJoineeChecklist.find_or_create_by_description('6 Passport size photographs', :group_id=>group1.id, :checklist_id=>1, :report_column_name=>"Passport Photos")
NewJoineeChecklist.find_or_create_by_description('Class X/ Higher Secondary Certificate along with Mark sheet', :group_id=>education_group.id, :checklist_id=>2, :report_column_name=>"Class X")
NewJoineeChecklist.find_or_create_by_description('Class XII/ Senior Secondary Certificate along with Mark sheet', :group_id=>education_group.id, :checklist_id=>3, :report_column_name=>"Class XII")
NewJoineeChecklist.find_or_create_by_description('Graduation/ Degree Certificate along with Mark sheet', :group_id=>education_group.id, :checklist_id=>4, :report_column_name=>"Graduation")
NewJoineeChecklist.find_or_create_by_description('Latest salary slip or salary certificate', :group_id=>visa_group.id, :checklist_id=>5, :report_column_name=>"Salary Slip")
NewJoineeChecklist.find_or_create_by_description('relieving letters from all the previous organizations worked in.(Required for immigration purposes)', :group_id=>visa_group.id, :checklist_id=>6, :report_column_name=>"Relieving Letters")
NewJoineeChecklist.find_or_create_by_description('You offer/appointment letters from all the previous organization worked in. (Required for immigration purposes)', :group_id=>visa_group.id, :checklist_id=>7, :report_column_name=>"Offer Letters")
NewJoineeChecklist.find_or_create_by_description('Copy of the passport - all pages (in case you have travelled to the US on a H1 visa, then a copy of that)', :group_id=>visa_group.id, :checklist_id=>8, :report_column_name=>"Passport Copies")
NewJoineeChecklist.find_or_create_by_description('In case of H1: also, the educational evaluation that the company did at that time', :group_id=>visa_group.id, :checklist_id=>9, :report_column_name=>"Educational Evaluation")
NewJoineeChecklist.find_or_create_by_description('PAN card copy', :group_id=>tax_group.id, :checklist_id=>10, :report_column_name=>"Pan Card")
NewJoineeChecklist.find_or_create_by_description('Existing PF number', :group_id=>tax_group.id, :checklist_id=>11, :report_column_name=>"PF No.")
NewJoineeChecklist.find_or_create_by_description('Previous 3 Financial Yar Income Tax Return copies. (Required for immigration purposes)', :group_id=>tax_group.id, :checklist_id=>12, :report_column_name=>"Tax Return")
NewJoineeChecklist.find_or_create_by_description('Form 16 or a TDS Certificate from last organisation worked in. (Required for calculating Tax for the Financial year)', :group_id=>tax_group.id, :checklist_id=>13, :report_column_name=>"Form 16 or DSD")
NewJoineeChecklist.find_or_create_by_description('Date of birth details of all dependents', :group_id=>dependent_group.id, :checklist_id=>14, :report_column_name=>"Dependents D.O.B")

Letterhead.find_or_create_by_office_name('Gurgaon', :template_path => "doc/templates/Gurgaon Letterhead.pdf")
Letterhead.find_or_create_by_office_name('Pune', :template_path => "doc/templates/Pune Letterhead.pdf")
Letterhead.find_or_create_by_office_name('Bangalore', :template_path => "doc/templates/Bangalore Letterhead.pdf")
Letterhead.find_or_create_by_office_name('Chennai', :template_path => "doc/templates/Chennai Letterhead.pdf")
