class RefreshSchemerForMigration < ActiveRecord::Migration
  def self.up
    change_column(:Account, :AccountID, :string, :limit=>36, :null=>false)
    change_column(:Account, :IndustryId, :string, :limit=>36)
    change_column(:Account, :SalesLeaderID, :string, :limit=>36)
    change_column(:Assignment, :AssignmentID, :string, :limit => 36, :null => false)
    change_column(:Assignment, :ProjectID, :string, :limit => 36, :null => false)
    change_column(:Assignment, :ResourceID, :string, :limit => 36, :null => false)
    change_column(:Assignment, :RoleID, :string, :limit => 36, :null => false)
    change_column(:Audit, :AuditID, :string, :limit => 36, :null => false)
    change_column(:Audit_arch, :AuditID, :string, :limit => 36, :null => false)
    change_column(:Country, :CountryID, :string, :limit => 36, :null => false)
    change_column(:Country, :CurrencyID, :string, :limit => 36, :null => false)
    change_column(:Currency, :CurrencyID, :string, :limit => 36, :null => false)
    change_column(:History, :HistoryID, :string, :limit => 36, :null => false)
    change_column(:History, :ResourceID, :string, :limit => 36, :null => false)
    change_column(:History, :locations_id, :string, :limit => 36, :null => false)
    change_column(:Industry, :IndustryID, :string, :limit => 36, :null => false)
    change_column(:LEVELS, :LevelsID, :string, :limit => 36, :null => false)
    change_column(:LEVELS, :TitleLevelID, :string, :limit => 36)
    change_column(:NonWorkingDay, :NonWorkingDateID, :string, :limit => 36, :null => false)
    change_column(:NonWorkingDay, :CountryID, :string, :limit => 36)
    change_column(:PaymentStream, :PaymentStreamID, :string, :limit => 36, :null => false)
    change_column(:PaymentStream, :ProjectID, :string, :limit => 36, :null => false)
    change_column(:PaymentStream, :CountryID, :string, :limit => 36)
    change_column(:PlannedRevenue, :PlannedRevenueID, :string, :limit => 36, :null => false)
    change_column(:PlannedRevenue, :CountryID, :string, :limit => 36, :null => false)
    change_column(:Project, :ProjectID, :string, :limit => 36, :null => false)
    change_column(:Project, :AccountID, :string, :limit => 36, :null => false)
    change_column(:Project, :CountryID, :string, :limit => 36, :null => false)
    change_column(:Project, :IndustryID, :string, :limit => 36)
    change_column(:Project, :SalesLeaderID, :string, :limit => 36, :null => false)
    change_column(:Project, :SponsorID, :string, :limit => 36, :null => false)
    change_column(:Project, :SolutionArchitectID, :string, :limit => 36)
    change_column(:Project, :TWOfferingID, :string, :limit => 36)
    change_column(:ProjectDistributionCountry, :ProjectDistributionCountryID, :string, :limit => 36, :null=>false)
    change_column(:ProjectDistributionCountry, :ProjectID, :string, :limit => 36, :null=>false)
    change_column(:ProjectDistributionCountry, :DistributedCountryID, :string, :limit => 36, :null=>false)
    change_column(:Resource, :ResourceID, :string, :limit => 36, :null=>false)
    change_column(:Resource, :LevelId, :string, :limit => 36)
    change_column(:Resource, :LocationID, :string, :limit => 36)
    change_column(:Resource, :CurrentLocationID, :string, :limit => 36)
    change_column(:Resource, :ExchangeID, :string, :limit => 36)
    change_column(:Role, :RoleID, :string, :limit => 36, :null=>false)
    change_column(:TWOffering, :TWOfferingID, :string, :limit => 36, :null=>false)
    change_column(:Title, :TitleID, :string, :limit => 36, :null=>false)


  end

  def self.down
    change_column(:Title, :TitleID, :string, :limit => 16, :null=>false)
    change_column(:TWOffering, :TWOfferingID, :string, :limit => 16, :null=>false)
    change_column(:Role, :RoleID, :string, :limit => 16, :null=>false)
    change_column(:Resource, :ExchangeID, :string, :limit => 16)
    change_column(:Resource, :CurrentLocationID, :string, :limit => 16)
    change_column(:Resource, :LocationID, :string, :limit => 16)
    change_column(:Resource, :LevelId, :string, :limit => 16)
    change_column(:Resource, :ResourceID, :string, :limit => 16, :null=>false)
    change_column(:ProjectDistributionCountry, :DistributedCountryID, :string, :limit => 16, :null=>false)
    change_column(:ProjectDistributionCountry, :ProjectID, :string, :limit => 16, :null=>false)
    change_column(:ProjectDistributionCountry, :ProjectDistributionCountryID, :string, :limit => 16, :null=>false)
    change_column(:Project, :TWOfferingID, :string, :limit => 16)
    change_column(:Project, :SolutionArchitectID, :string, :limit => 16)
    change_column(:Project, :SponsorID, :string, :limit => 16, :null => false)
    change_column(:Project, :SalesLeaderID, :string, :limit => 16, :null => false)
    change_column(:Project, :IndustryID, :string, :limit => 16)
    change_column(:Project, :CountryID, :string, :limit => 16)
    change_column(:Project, :AccountID, :string, :limit => 16, :null => false)
    change_column(:Project, :ProjectID, :string, :limit => 16, :null => false)
    change_column(:PlannedRevenue, :CountryID, :string, :limit => 16, :null => false)
    change_column(:PlannedRevenue, :PlannedRevenueID, :string, :limit => 16, :null => false)
    change_column(:PaymentStream, :CountryID, :string, :limit => 16)
    change_column(:PaymentStream, :ProjectID, :string, :limit => 16, :null => false)
    change_column(:PaymentStream, :PaymentStreamID, :string, :limit => 16, :null => false)
    change_column(:NonWorkingDay, :CountryID, :string, :limit => 16, :null => false)
    change_column(:NonWorkingDay, :NonWorkingDateID, :string, :limit => 16, :null => false)
    change_column(:LEVELS, :LevelsID, :string, :limit => 16, :null => false)
    change_column(:LEVELS, :TitleLevelID, :string, :limit => 16)
    change_column(:Industry, :IndustryID, :string, :limit => 16, :null => false)
    change_column(:History, :locations_id, :string, :limit => 16, :null => false)
    change_column(:History, :HistoryID, :string, :limit => 16, :null => false)
    change_column(:History, :ResourceID, :string, :limit => 16, :null => false)
    change_column(:Currency, :CurrencyID, :string, :limit => 16, :null => false)
    change_column(:Country, :CurrencyID, :string, :limit => 16, :null => false)
    change_column(:Country, :CountryID, :string, :limit => 16, :null => false)
    change_column(:Audit_arch, :AuditID, :string, :limit => 16, :null => false)
    change_column(:Audit, :AuditID, :string, :limit => 16, :null => false)
    change_column(:Assignment, :RoleID, :string, :limit => 16, :null => false)
    change_column(:Assignment, :ResourceID, :string, :limit => 16, :null => false)
    change_column(:Assignment, :ProjectID, :string, :limit => 16, :null => false)
    change_column(:Assignment, :AssignmentID, :string, :limit => 16, :null => false)
    change_column(:Account, :SalesLeaderID, :string, :limit=>16)
    change_column(:Account, :IndustryId, :string, :limit=>16)
    change_column(:Account, :AccountID, :string, :limit=>16, :null=>false)


  end
end
